import type { EmissionFactor } from './types.js';

export const TEXTILE_EMISSION_FACTORS: Record<string, EmissionFactor> = {
  cotton_conventional: {
    factorKey: 'cotton_conventional',
    name: 'Coton conventionnel',
    category: 'natural_plant',
    carbonKgCo2e: 4.85,
    waterM3: 8.50,
    eutrophicationKgP: 0.0035,
    microplasticsRisk: 'A',
    circularityRecyclabilityPct: 90,
  },
  cotton_organic: {
    factorKey: 'cotton_organic',
    name: 'Coton Biologique Certifié (GOTS / OCS)',
    category: 'natural_plant',
    carbonKgCo2e: 2.10,
    waterM3: 2.20,
    eutrophicationKgP: 0.0009,
    microplasticsRisk: 'A',
    circularityRecyclabilityPct: 95,
  },
  linen: {
    factorKey: 'linen',
    name: 'Lin d’Europe / Teillage mécanique',
    category: 'natural_plant',
    carbonKgCo2e: 1.45,
    waterM3: 0.85,
    eutrophicationKgP: 0.00045,
    microplasticsRisk: 'A',
    circularityRecyclabilityPct: 98,
  },
  hemp: {
    factorKey: 'hemp',
    name: 'Chanvre textile',
    category: 'natural_plant',
    carbonKgCo2e: 1.30,
    waterM3: 0.70,
    eutrophicationKgP: 0.0004,
    microplasticsRisk: 'A',
    circularityRecyclabilityPct: 98,
  },
  viscose_conventional: {
    factorKey: 'viscose_conventional',
    name: 'Viscose conventionnelle',
    category: 'manmade_cellulosic',
    carbonKgCo2e: 5.20,
    waterM3: 3.40,
    eutrophicationKgP: 0.0028,
    microplasticsRisk: 'A',
    circularityRecyclabilityPct: 80,
  },
  lyocell_tencel: {
    factorKey: 'lyocell_tencel',
    name: 'Lyocell / Tencel boucle fermée',
    category: 'manmade_cellulosic',
    carbonKgCo2e: 2.30,
    waterM3: 1.10,
    eutrophicationKgP: 0.00075,
    microplasticsRisk: 'A',
    circularityRecyclabilityPct: 92,
  },
  wool_conventional: {
    factorKey: 'wool_conventional',
    name: 'Laine conventionnelle',
    category: 'natural_animal',
    carbonKgCo2e: 24.50,
    waterM3: 4.20,
    eutrophicationKgP: 0.0125,
    microplasticsRisk: 'A',
    circularityRecyclabilityPct: 85,
  },
  wool_rws: {
    factorKey: 'wool_rws',
    name: 'Laine Certifiée RWS / Éco-pâturage',
    category: 'natural_animal',
    carbonKgCo2e: 14.80,
    waterM3: 2.50,
    eutrophicationKgP: 0.0062,
    microplasticsRisk: 'A',
    circularityRecyclabilityPct: 92,
  },
  silk: {
    factorKey: 'silk',
    name: 'Soie naturelle de mûrier',
    category: 'natural_animal',
    carbonKgCo2e: 18.20,
    waterM3: 5.10,
    eutrophicationKgP: 0.0084,
    microplasticsRisk: 'A',
    circularityRecyclabilityPct: 80,
  },
  polyester_virgin: {
    factorKey: 'polyester_virgin',
    name: 'Polyester Vierge (PET)',
    category: 'synthetic',
    carbonKgCo2e: 5.60,
    waterM3: 0.12,
    eutrophicationKgP: 0.0018,
    microplasticsRisk: 'D',
    circularityRecyclabilityPct: 65,
  },
  polyester_recycled: {
    factorKey: 'polyester_recycled',
    name: 'Polyester Recyclé Certifié (GRS / rPET)',
    category: 'synthetic',
    carbonKgCo2e: 2.35,
    waterM3: 0.05,
    eutrophicationKgP: 0.00085,
    microplasticsRisk: 'D',
    circularityRecyclabilityPct: 80,
  },
  polyamide_nylon_virgin: {
    factorKey: 'polyamide_nylon_virgin',
    name: 'Polyamide 6/6.6 Vierge (Nylon)',
    category: 'synthetic',
    carbonKgCo2e: 7.90,
    waterM3: 0.18,
    eutrophicationKgP: 0.0024,
    microplasticsRisk: 'D',
    circularityRecyclabilityPct: 60,
  },
  polyamide_recycled: {
    factorKey: 'polyamide_recycled',
    name: 'Polyamide Recyclé (Econyl / GRS)',
    category: 'synthetic',
    carbonKgCo2e: 3.40,
    waterM3: 0.08,
    eutrophicationKgP: 0.0011,
    microplasticsRisk: 'D',
    circularityRecyclabilityPct: 78,
  },
  elastane: {
    factorKey: 'elastane',
    name: 'Élasthanne / Spandex',
    category: 'synthetic',
    carbonKgCo2e: 7.20,
    waterM3: 0.15,
    eutrophicationKgP: 0.0021,
    microplasticsRisk: 'E',
    circularityRecyclabilityPct: 25,
  },
};

export const STANDARD_GARMENT_WEIGHTS_KG: Record<string, number> = {
  jeans: 0.650,
  denim: 0.650,
  jeans_denim: 0.650,
  tshirt: 0.180,
  tee: 0.180,
  jacket: 0.950,
  coat: 0.950,
  outerwear: 0.950,
  dress: 0.350,
  robe: 0.350,
  knitwear: 0.450,
  sweater: 0.450,
  pull: 0.450,
  shirt: 0.220,
  chemise: 0.220,
  pants: 0.400,
  trousers: 0.400,
  pantalon: 0.400,
  other: 0.400,
};
