import type { GreenClaimRule } from './types.js';

export const STATIC_GREEN_CLAIMS_RULES: GreenClaimRule[] = [
  {
    ruleCode: 'GENERIC_ECO_CLAIM',
    category: 'prohibited_generic_term',
    ruleTitle: 'Interdiction des allégations génériques vagues',
    description: 'Les mentions vagues telles que "éco-responsable", "vert", "durable", "ami de la nature" sont interdites sans excellence environnementale certifiée.',
    targetPattern: '(éco-responsable|eco-responsable|vert|green|durable|sustainable|naturel|bon pour la planète|ami de la nature)',
    severity: 'critical',
    legalBasis: 'Directive (UE) 2024/825 Art. 2',
    remediationAdvice: 'Remplacer par une allégation spécifique et mesurable (ex: "Confectionné avec 98% de coton biologique certifié GOTS").',
  },
  {
    ruleCode: 'CARBON_NEUTRAL_BAN',
    category: 'carbon_neutrality_ban',
    ruleTitle: 'Interdiction des allégations de neutralité carbone basées sur la compensation',
    description: 'Les allégations selon lesquelles un produit a un impact neutre, réduit ou positif sur le climat grâce à des crédits carbone sont interdites.',
    targetPattern: '(neutre en carbone|neutralité carbone|carbon neutral|zéro émission|compensé carbone|climate positive)',
    severity: 'critical',
    legalBasis: 'Directive (UE) 2024/825 Art. 2.2',
    remediationAdvice: 'Indiquer uniquement l’empreinte carbone réelle mesurée en kg CO2e selon la méthode PEF, sans alléguer la neutralité.',
  },
  {
    ruleCode: 'ORGANIC_UNSUBSTANTIATED',
    category: 'organic_claim_proof',
    ruleTitle: 'Allégation biologique requérant un certificat de transaction valide',
    description: 'Toute allégation mentionnant "biologique", "organic", "bio" doit être étayée par un certificat GOTS ou OCS actif pour la matière concernée.',
    targetPattern: '(bio|biologique|organic)',
    severity: 'high',
    legalBasis: 'Règlement (UE) 2018/848 & Guide DGCCRF',
    remediationAdvice: 'Rattacher un certificat GOTS ou OCS valide et vérifier que le pourcentage de fibre bio déclaré est supérieur ou égal à 70%.',
  },
  {
    ruleCode: 'RECYCLED_UNSUBSTANTIATED',
    category: 'recycled_content_threshold',
    ruleTitle: 'Allégation recyclée requérant preuve de chaîne de contrôle',
    description: 'Les mentions "recyclé", "fibres recyclées", "rPET" exigent une traçabilité GRS ou RCS prouvant le pourcentage de contenu recyclé pré ou post-consommation.',
    targetPattern: '(recyclé|recycled|rpet|econyl)',
    severity: 'high',
    legalBasis: 'Norme ISO 14021 & Directive Green Claims',
    remediationAdvice: 'Associer un certificat GRS ou RCS et spécifier le pourcentage exact de matière recyclée dans la composition.',
  },
  {
    ruleCode: 'BIODEGRADABLE_MISLEADING',
    category: 'prohibited_generic_term',
    ruleTitle: 'Allégation de biodégradabilité trompeuse',
    description: 'Revendiquer la biodégradabilité globale d’un vêtement est interdit si certaines composantes (fils, boutons, élasthanne) ne le sont pas en conditions naturelles.',
    targetPattern: '(biodégradable|biodegradable|compostable)',
    severity: 'critical',
    legalBasis: 'Loi AGEC Art. 13 & Directive Green Claims',
    remediationAdvice: 'Préciser les composants individuels biodégradables et les normes industrielles de référence (ex: EN 13432).',
  },
];
