/* ==========================================================================
   TRACEFAB — portee i18n du DPP public (dpp/).

   Migration du dictionnaire inline dppLangs vers le catalogue unique.

   Constat releve pendant la migration : sur les 10 cles du dictionnaire,
   une seule, badgeEu, etait reellement lue par la page. Les neuf autres
   etaient traduites dans sept langues et jamais affichees. Elles sont
   conservees ici parce qu'elles correspondent aux sections que le DPP
   public doit exposer et qu'elles serviront a l'extraction de la copie
   (chantier 7), mais elles restent inutilisees a ce jour et le test
   d'integrite les signale comme telles plutot que de les faire passer
   pour de la couverture acquise.

   Usage : node scripts/build_dpp_i18n.mjs [--check]
   ========================================================================== */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const I18N = join(ROOT, 'assets/i18n');
const CHECK = process.argv.includes('--check');
const LANGS = ["en", "fr", "de", "it", "es", "nl", "pt"];

// cle: [en, fr, de, it, es, nl, pt]
const T = {
  // Reformule au chantier 7. Le libelle affiche « DPP Compliant » / « DPP
  // Conforme », c'est-a-dire exactement la revendication que le test
  // test_pef_chantier3.mjs interdit dans le balisage depuis le 7 octobre.
  // L'indirection i18n contournait ce garde-fou : la page rendait la
  // mention a l'ecran. On cite le referentiel sans affirmer la conformite.
  badgeEu: ["EU ESPR / DPP format", "Format EU ESPR / DPP", "EU-ESPR-/DPP-Format", "Formato UE ESPR / DPP", "Formato UE ESPR / DPP", "EU ESPR-/DPP-formaat", "Formato UE ESPR / DPP"],
  verifiedOrigin: ["✓ Verified Provenance", "✓ Provenance Vérifiée", "✓ Verifizierte Herkunft", "✓ Provenienza Verificata", "✓ Procedencia Verificada", "✓ Geverifieerde Herkomst", "✓ Proveniência Verificada"],  // non utilisee a ce jour (voir note en tete)
  composition: ["Material Composition", "Composition des Matières", "Materialzusammensetzung", "Composizione Materiali", "Composición de Materiales", "Materiaalsamenstelling", "Composição dos Materiais"],  // non utilisee a ce jour (voir note en tete)
  traceability: ["Supply Chain Traceability", "Traçabilité de la Chaîne", "Lieferketten-Rückverfolgbarkeit", "Tracciabilità della Filiera", "Trazabilidad de la Cadena", "Traceerbaarheid Toeleveringsketen", "Rastreabilidade da Cadeia"],  // non utilisee a ce jour (voir note en tete)
  operations: ["Operations & Facilities", "Opérations & Ateliers", "Betriebe & Werkstätten", "Operazioni & Stabilimenti", "Operaciones e Instalaciones", "Bewerkingen & Faciliteiten", "Operações & Instalações"],  // non utilisee a ce jour (voir note en tete)
  circularity: ["Circularity & Care", "Circularité & Entretien", "Kreislaufwirtschaft & Pflege", "Circolarità & Cura", "Circularidad y Cuidado", "Circulariteit & Onderhoud", "Circularidade & Cuidados"],  // non utilisee a ce jour (voir note en tete)
  repairScore: ["Repairability Index", "Indice de Réparabilité", "Reparierbarkeitsindex", "Indice di Riparabilità", "Índice de Reparabilidad", "Repareerbaarheidsindex", "Índice de Reparabilidade"],  // non utilisee a ce jour (voir note en tete)
  carbon: ["Environmental Footprint", "Empreinte Environnementale", "Ökologischer Fußabdruck", "Impronta Ambientale", "Huella Ambiental", "Milieu-voetafdruk", "Pegada Ambiental"],  // non utilisee a ce jour (voir note en tete)
  passcode: ["SHA-256 Verified Seal", "Sceau Scellé SHA-256", "SHA-256 Verifiziertes Siegel", "Sigillo Verificato SHA-256", "Sello Verificado SHA-256", "SHA-256 Geverifieerd Zegel", "Selo Verificado SHA-256"],  // non utilisee a ce jour (voir note en tete)
  viewCert: ["View Audit Certificate", "Voir le certificat d'audit", "Audit-Zertifikat ansehen", "Visualizza certificato audit", "Ver certificado de auditoría", "Auditcertificaat bekijken", "Ver certificado de auditoria"],  // non utilisee a ce jour (voir note en tete)
  hdrOfficial: ["Official Digital Product Passport", "Passeport Numérique Officiel", "Offizieller digitaler Produktpass", "Passaporto digitale ufficiale del prodotto", "Pasaporte digital de producto oficial", "Officieel digitaal productpaspoort", "Passaporte digital de produto oficial"],
  heroDesc: ["Iconic T-shirt in 185 gsm regenerative organic cotton jersey. Traced from seed to finished garment with 100% documented evidence.", "T-shirt iconique en jersey de coton biologique régénératif 185g/m². Tracé de la graine au vêtement confectionné avec 100% de preuves documentées.", "Ikonisches T-Shirt aus regenerativem Bio-Baumwolljersey, 185 g/m². Von der Saat bis zum fertigen Kleidungsstück mit 100 % dokumentierten Nachweisen rückverfolgt.", "T-shirt iconica in jersey di cotone biologico rigenerativo da 185 g/m². Tracciata dal seme al capo finito con il 100% di prove documentate.", "Camiseta icónica en jersey de algodón orgánico regenerativo de 185 g/m². Trazada desde la semilla hasta la prenda acabada con el 100% de pruebas documentadas.", "Iconisch T-shirt van regeneratieve biologische katoenjersey van 185 g/m². Getraceerd van zaad tot afgewerkt kledingstuk met 100% gedocumenteerd bewijs.", "T-shirt icónica em jersey de algodão biológico regenerativo de 185 g/m². Rastreada da semente à peça acabada com 100% de provas documentadas."],
  heroCertified: ["✓ 100% documented materials", "✓ 100% Matières documentées", "✓ 100 % dokumentierte Materialien", "✓ 100% materiali documentati", "✓ 100% materiales documentados", "✓ 100% gedocumenteerde materialen", "✓ 100% materiais documentados"],
  heroMadeIn: ["Made in Portugal", "Fabriqué au Portugal", "Hergestellt in Portugal", "Fabbricato in Portogallo", "Fabricado en Portugal", "Gemaakt in Portugal", "Fabricado em Portugal"],
  offlineWallet: ["Offline digital passport and mobile wallet", "Passeport Numérique Hors-Ligne & Portefeuille Mobile", "Offline-Digitalpass und mobile Wallet", "Passaporto digitale offline e wallet mobile", "Pasaporte digital sin conexión y cartera móvil", "Offline digitaal paspoort en mobiele wallet", "Passaporte digital offline e carteira móvel"],
  tabMaterials: ["Materials (2)", "Matières (2)", "Materialien (2)", "Materiali (2)", "Materiales (2)", "Materialen (2)", "Materiais (2)"],
  tabTraceability: ["Traceability (7)", "Traçabilité (7)", "Rückverfolgbarkeit (7)", "Tracciabilità (7)", "Trazabilidad (7)", "Traceerbaarheid (7)", "Rastreabilidade (7)"],
  tabImpact: ["Eco-score and LCA", "Éco-Score & ACV", "Öko-Score und Ökobilanz", "Eco-score e LCA", "Ecopuntuación y ACV", "Eco-score en LCA", "Eco-score e ACV"],
  tabCircularity: ["Repairability and end of life", "Réparabilité & Fin de Vie", "Reparierbarkeit und Lebensende", "Riparabilità e fine vita", "Reparabilidad y fin de vida", "Repareerbaarheid en einde levensduur", "Reparabilidade e fim de vida"],
  tabsAria: ["Passport sections", "Sections du Passeport", "Passabschnitte", "Sezioni del passaporto", "Secciones del pasaporte", "Paspoortsecties", "Secções do passaporte"],
  matTitle: ["Fibre composition and origin", "Composition & Origine des Fibres", "Faserzusammensetzung und Herkunft", "Composizione e origine delle fibre", "Composición y origen de las fibras", "Vezelsamenstelling en herkomst", "Composição e origem das fibras"],
  matTraced: ["100% traced", "100% Tracé", "100 % rückverfolgt", "100% tracciato", "100% trazado", "100% getraceerd", "100% rastreado"],
  matDesc: ["Declaration stated in line with the European textile regulation. Third-party review is reported only when it has been performed.", "Déclaration établie selon le règlement textile européen. Un contrôle par tiers n'est indiqué que lorsqu'il a été réalisé.", "Erklärung gemäß der europäischen Textilverordnung. Eine Prüfung durch Dritte wird nur angezeigt, wenn sie stattgefunden hat.", "Dichiarazione redatta secondo il regolamento tessile europeo. Il controllo di terze parti è indicato solo se è stato effettuato.", "Declaración establecida según el reglamento textil europeo. El control por terceros solo se indica cuando se ha realizado.", "Verklaring opgesteld volgens de Europese textielverordening. Controle door derden wordt alleen vermeld als die heeft plaatsgevonden.", "Declaração estabelecida segundo o regulamento têxtil europeu. O controlo por terceiros só é indicado quando foi realizado."],
  matCombed: ["85% combed organic cotton", "85% Coton Biologique Peigné", "85 % gekämmte Bio-Baumwolle", "85% cotone biologico pettinato", "85% algodón orgánico peinado", "85% gekamde biologische katoen", "85% algodão biológico penteado"],
  matRecycled: ["15% pre-consumer recycled cotton", "15% Coton Recyclé Pré-consommation", "15 % Pre-Consumer-Recyclingbaumwolle", "15% cotone riciclato pre-consumo", "15% algodón reciclado preconsumo", "15% pre-consumer gerecyclede katoen", "15% algodão reciclado pré-consumo"],
  matRecycledDesc: ["Recovery of workshop cutting offcuts", "Revalorisation des chutes de coupe d'atelier", "Verwertung von Zuschnittresten aus der Werkstatt", "Valorizzazione degli scarti di taglio di laboratorio", "Revalorización de los recortes de corte del taller", "Opwaardering van snijresten uit het atelier", "Valorização dos retalhos de corte da oficina"],
  matBiodeg: ["100% biodegradable natural fibres.", "100% fibres naturelles biodégradables.", "100 % biologisch abbaubare Naturfasern.", "100% fibre naturali biodegradabili.", "100% fibras naturales biodegradables.", "100% biologisch afbreekbare natuurlijke vezels.", "100% fibras naturais biodegradáveis."],
  chainTitle: ["Chain of custody and factories", "Chaîne de Contrôle & Usines", "Lieferkette und Werke", "Catena di custodia e stabilimenti", "Cadena de custodia y fábricas", "Chain of custody en fabrieken", "Cadeia de custódia e fábricas"],
  chainTiers: ["5 validated tiers", "5 Échelons Validés", "5 validierte Stufen", "5 livelli convalidati", "5 niveles validados", "5 gevalideerde niveaus", "5 níveis validados"],
  chainDesc: ["Certification of each industrial step relies on an audited transaction certificate (TC) — indicated only when it exists.", "La certification de chaque étape industrielle repose sur un certificat de transaction (TC) audité — indiqué lorsqu'il existe.", "Die Zertifizierung jedes industriellen Schritts stützt sich auf ein geprüftes Transaktionszertifikat (TC) — angezeigt, sofern vorhanden.", "La certificazione di ogni fase industriale si basa su un certificato di transazione (TC) sottoposto ad audit — indicato solo se presente.", "La certificación de cada etapa industrial se basa en un certificado de transacción (TC) auditado — indicado solo cuando existe.", "Certificering van elke industriële stap steunt op een geaudit transactiecertificaat (TC) — alleen vermeld als het bestaat.", "A certificação de cada etapa industrial baseia-se num certificado de transação (TC) auditado — indicado apenas quando existe."],
  chainFibre: ["Fibre cultivation", "Culture de la Fibre", "Faseranbau", "Coltivazione della fibra", "Cultivo de la fibra", "Vezelteelt", "Cultivo da fibra"],
  chainYarn: ["✓ High-tenacity combed yarn Ne 30/1", "✓ Fil peigné haute résistance Ne 30/1", "✓ Hochfestes Kammgarn Ne 30/1", "✓ Filato pettinato ad alta tenacità Ne 30/1", "✓ Hilo peinado de alta tenacidad Ne 30/1", "✓ Hoogsterk gekamd garen Ne 30/1", "✓ Fio penteado de alta tenacidade Ne 30/1"],
  chainClosed: ["✓ Closed loop and effluent treatment (STeP)", "✓ Circuit fermé & traitement des rejets (STeP)", "✓ Geschlossener Kreislauf und Abwasserbehandlung (STeP)", "✓ Circuito chiuso e trattamento dei reflui (STeP)", "✓ Circuito cerrado y tratamiento de efluentes (STeP)", "✓ Gesloten kringloop en afvalwaterbehandeling (STeP)", "✓ Circuito fechado e tratamento de efluentes (STeP)"],
  impTitle: ["Environmental assessment and eco-score", "Évaluation Environnementale & Éco-Score", "Umweltbewertung und Öko-Score", "Valutazione ambientale ed eco-score", "Evaluación ambiental y ecopuntuación", "Milieubeoordeling en eco-score", "Avaliação ambiental e eco-score"],
  impMethod: ["AGEC Act and ESPR methodology", "Méthodologie Loi AGEC & ESPR", "Methodik AGEC-Gesetz und ESPR", "Metodologia Legge AGEC ed ESPR", "Metodología Ley AGEC y ESPR", "Methodologie AGEC-wet en ESPR", "Metodologia Lei AGEC e ESPR"],
  impDesc: ["Full life-cycle assessment (LCA) following the European PEFCR Apparel & Footwear 2024 methodology.", "Analyse du cycle de vie complet (ACV) selon la méthodologie européenne PEFCR Apparel & Footwear 2024.", "Vollständige Ökobilanz (LCA) nach der europäischen Methodik PEFCR Apparel & Footwear 2024.", "Analisi del ciclo di vita completa (LCA) secondo la metodologia europea PEFCR Apparel & Footwear 2024.", "Análisis de ciclo de vida completo (ACV) según la metodología europea PEFCR Apparel & Footwear 2024.", "Volledige levenscyclusanalyse (LCA) volgens de Europese methodologie PEFCR Apparel & Footwear 2024.", "Análise de ciclo de vida completa (ACV) segundo a metodologia europeia PEFCR Apparel & Footwear 2024."],
  impEcoScore: ["European textile eco-score", "Éco-Score Textile Européen", "Europäischer Textil-Öko-Score", "Eco-score tessile europeo", "Ecopuntuación textil europea", "Europese textiel-eco-score", "Eco-score têxtil europeu"],
  impEcoDesign: ["Eco-design index", "Indice d'Éco-Conception", "Ökodesign-Index", "Indice di eco-progettazione", "Índice de ecodiseño", "Ecodesign-index", "Índice de ecoconceção"],
  impCarbon: ["Actual carbon footprint", "Empreinte Carbone Réelle", "Tatsächlicher CO₂-Fußabdruck", "Impronta di carbonio reale", "Huella de carbono real", "Werkelijke koolstofvoetafdruk", "Pegada de carbono real"],
  impVsRef: ["-48% versus the conventional baseline (PEFCR 2024).", "-48% vs référence conventionnelle (PEFCR 2024).", "-48 % gegenüber der konventionellen Referenz (PEFCR 2024).", "-48% rispetto al riferimento convenzionale (PEFCR 2024).", "-48% frente a la referencia convencional (PEFCR 2024).", "-48% ten opzichte van de conventionele referentie (PEFCR 2024).", "-48% face à referência convencional (PEFCR 2024)."],
  impThanksTo: ["-64% thanks to rain-fed organic cotton (GOTS certification to be verified).", "-64% grâce au coton bio pluvial (certification GOTS à vérifier).", "-64 % dank Regenfeld-Bio-Baumwolle (GOTS-Zertifizierung zu prüfen).", "-64% grazie al cotone biologico pluviale (certificazione GOTS da verificare).", "-64% gracias al algodón orgánico de secano (certificación GOTS por verificar).", "-64% dankzij regengevoede biologische katoen (GOTS-certificering te verifiëren).", "-64% graças ao algodão biológico de sequeiro (certificação GOTS a verificar)."],
  impCircular: ["Circularity and recyclability", "Circularité & Recyclabilité", "Kreislauffähigkeit und Recyclingfähigkeit", "Circolarità e riciclabilità", "Circularidad y reciclabilidad", "Circulariteit en recycleerbaarheid", "Circularidade e reciclabilidade"],
  impMonoFibre: ["Single-material fibre, recyclable in a closed loop.", "Fibre monomatière recyclable en boucle fermée.", "Monomaterial-Faser, im geschlossenen Kreislauf recycelbar.", "Fibra monomateriale riciclabile in circuito chiuso.", "Fibra monomaterial reciclable en circuito cerrado.", "Monomateriaalvezel, recycleerbaar in een gesloten kringloop.", "Fibra monomaterial reciclável em circuito fechado."],
  careTitle: ["Care advice and repairability", "Conseils d'Entretien & Réparabilité", "Pflegehinweise und Reparierbarkeit", "Consigli di cura e riparabilità", "Consejos de cuidado y reparabilidad", "Onderhoudsadvies en repareerbaarheid", "Conselhos de conservação e reparabilidade"],
  careIntro: ["Extending the life of your garment divides its overall carbon footprint by three.", "Prolonger la durée de vie de votre vêtement divise par 3 son empreinte carbone globale.", "Die Lebensdauer Ihres Kleidungsstücks zu verlängern, drittelt seinen gesamten CO₂-Fußabdruck.", "Prolungare la vita del capo divide per tre la sua impronta di carbonio complessiva.", "Prolongar la vida de su prenda divide por tres su huella de carbono total.", "Het verlengen van de levensduur van uw kledingstuk deelt de totale koolstofvoetafdruk door drie.", "Prolongar a vida da sua peça divide por três a sua pegada de carbono global."],
  careWash: ["Delicate wash at 30°C", "Lavage délicat à 30°C", "Schonwäsche bei 30 °C", "Lavaggio delicato a 30 °C", "Lavado delicado a 30 °C", "Fijne was op 30 °C", "Lavagem delicada a 30 °C"],
  careWashDesc: ["Preserves the cotton fibres and cuts energy use by 60%.", "Préserve les fibres de coton et réduit la consommation d'énergie de 60%.", "Schont die Baumwollfasern und senkt den Energieverbrauch um 60 %.", "Preserva le fibre di cotone e riduce il consumo energetico del 60%.", "Preserva las fibras de algodón y reduce el consumo de energía en un 60%.", "Beschermt de katoenvezels en verlaagt het energieverbruik met 60%.", "Preserva as fibras de algodão e reduz o consumo de energia em 60%."],
  careDry: ["Natural open-air drying", "Séchage naturel à l'air libre", "Natürliche Lufttrocknung", "Asciugatura naturale all'aria aperta", "Secado natural al aire libre", "Natuurlijk drogen in de buitenlucht", "Secagem natural ao ar livre"],
  careDryDesc: ["Tumble drying weakens the seams and uses 1.5 kWh per cycle.", "Le sèche-linge fragilise les coutures et consomme 1.5 kWh par cycle.", "Der Trockner schwächt die Nähte und verbraucht 1,5 kWh pro Zyklus.", "L'asciugatrice indebolisce le cuciture e consuma 1,5 kWh per ciclo.", "La secadora debilita las costuras y consume 1,5 kWh por ciclo.", "De droger verzwakt de naden en verbruikt 1,5 kWh per cyclus.", "A máquina de secar enfraquece as costuras e consome 1,5 kWh por ciclo."],
  careRepair: ["Free repair programme", "Programme de Réparation Gratuit", "Kostenloses Reparaturprogramm", "Programma di riparazione gratuito", "Programa de reparación gratuito", "Gratis reparatieprogramma", "Programa de reparação gratuito"],
  careRepairDesc: ["Seams and hems repairable for life through our partner network.", "Coutures et ourlets réparables à vie via notre réseau partenaire.", "Nähte und Säume lebenslang über unser Partnernetz reparierbar.", "Cuciture e orli riparabili a vita tramite la nostra rete di partner.", "Costuras y dobladillos reparables de por vida a través de nuestra red de socios.", "Naden en zomen levenslang repareerbaar via ons partnernetwerk.", "Costuras e bainhas reparáveis para toda a vida através da nossa rede de parceiros."],
  careRecyclability: ["Recyclability: 98%", "Recyclabilité : 98%", "Recyclingfähigkeit: 98 %", "Riciclabilità: 98%", "Reciclabilidad: 98%", "Recycleerbaarheid: 98%", "Reciclabilidade: 98%"],
  careRecyclDesc: ["Single-cotton fibre that can re-enter European recycling spinning mills.", "Fibre monocoton réintroduisible dans les filatures européennes de recyclage.", "Monobaumwollfaser, die in europäische Recycling-Spinnereien zurückgeführt werden kann.", "Fibra di solo cotone reintroducibile nelle filature europee di riciclo.", "Fibra de algodón puro reintroducible en las hilaturas europeas de reciclaje.", "Mono-katoenvezel die opnieuw in Europese recyclingspinnerijen kan worden ingebracht.", "Fibra de algodão único reintroduzível nas fiações europeias de reciclagem."],
  evTitle: ["Certificates and legal evidence", "Certificats & Preuves Légales", "Zertifikate und rechtliche Nachweise", "Certificati e prove legali", "Certificados y pruebas legales", "Certificaten en juridisch bewijs", "Certificados e provas legais"],
  evAudited: ["Audited", "Audité", "Geprüft", "Sottoposto ad audit", "Auditado", "Geauditeerd", "Auditado"],
  evDesc: ["Official documents admissible in European Union and DGCCRF compliance audits.", "Documents officiels opposables aux audits de conformité de l'Union Européenne et DGCCRF.", "Offizielle Dokumente, die bei Konformitätsprüfungen der Europäischen Union und der DGCCRF verwendbar sind.", "Documenti ufficiali opponibili agli audit di conformità dell'Unione europea e della DGCCRF.", "Documentos oficiales oponibles a las auditorías de conformidad de la Unión Europea y de la DGCCRF.", "Officiële documenten die inzetbaar zijn bij nalevingsaudits van de Europese Unie en de DGCCRF.", "Documentos oficiais oponíveis às auditorias de conformidade da União Europeia e da DGCCRF."],
  evIssuer: ["Accredited certification body: Control Union Certification B.V.", "Organisme certificateur accrédité : Control Union Certification B.V.", "Akkreditierte Zertifizierungsstelle: Control Union Certification B.V.", "Organismo di certificazione accreditato: Control Union Certification B.V.", "Organismo de certificación acreditado: Control Union Certification B.V.", "Geaccrediteerde certificerende instantie: Control Union Certification B.V.", "Organismo certificador acreditado: Control Union Certification B.V."],
  evChem: ["Analytical check for the absence of harmful chemical residues (Hohenstein).", "Contrôle analytique d'absence de résidus chimiques nocifs (Hohenstein).", "Analytische Prüfung auf Abwesenheit schädlicher chemischer Rückstände (Hohenstein).", "Controllo analitico dell'assenza di residui chimici nocivi (Hohenstein).", "Control analítico de ausencia de residuos químicos nocivos (Hohenstein).", "Analytische controle op de afwezigheid van schadelijke chemische residuen (Hohenstein).", "Controlo analítico da ausência de resíduos químicos nocivos (Hohenstein)."],
  evSmeta: ["SMETA 4-Pillar social audit (ethics and safety)", "Audit Social SMETA 4-Pillar (Éthique & Sécurité)", "SMETA-4-Säulen-Sozialaudit (Ethik und Sicherheit)", "Audit sociale SMETA 4-Pillar (etica e sicurezza)", "Auditoría social SMETA 4-Pillar (ética y seguridad)", "SMETA 4-Pillar sociale audit (ethiek en veiligheid)", "Auditoria social SMETA 4-Pillar (ética e segurança)"],
  evSmetaRef: ["Ref.: SEDEX-SMETA-2026-PT", "Réf : SEDEX-SMETA-2026-PT", "Ref.: SEDEX-SMETA-2026-PT", "Rif.: SEDEX-SMETA-2026-PT", "Ref.: SEDEX-SMETA-2026-PT", "Ref.: SEDEX-SMETA-2026-PT", "Ref.: SEDEX-SMETA-2026-PT"],
  evSmetaDesc: ["Decent pay, occupational health and union rights audited.", "Rémunération décente, santé au travail et droits syndicaux audités.", "Angemessene Vergütung, Arbeitsschutz und Gewerkschaftsrechte geprüft.", "Retribuzione dignitosa, salute sul lavoro e diritti sindacali sottoposti ad audit.", "Remuneración digna, salud laboral y derechos sindicales auditados.", "Fatsoenlijke beloning, arbeidsgezondheid en vakbondsrechten geauditeerd.", "Remuneração digna, saúde no trabalho e direitos sindicais auditados."],
  cirTitle: ["Repairability, recyclability and second life", "Réparabilité, Recyclabilité & Seconde Vie", "Reparierbarkeit, Recyclingfähigkeit und zweites Leben", "Riparabilità, riciclabilità e seconda vita", "Reparabilidad, reciclabilidad y segunda vida", "Repareerbaarheid, recycleerbaarheid en tweede leven", "Reparabilidade, reciclabilidade e segunda vida"],
  cirDesc: ["Official life-extension instructions, textile repairability index and approved take-back channels.", "Instructions officielles de prolongation de vie, indice de réparabilité textile et filières de reprise agréées.", "Offizielle Anleitungen zur Lebensverlängerung, Textil-Reparierbarkeitsindex und zugelassene Rücknahmewege.", "Istruzioni ufficiali di prolungamento della vita, indice di riparabilità tessile e filiere di ritiro autorizzate.", "Instrucciones oficiales de prolongación de vida, índice de reparabilidad textil y canales de recogida autorizados.", "Officiële instructies voor levensduurverlenging, textielrepareerbaarheidsindex en erkende terugnamekanalen.", "Instruções oficiais de prolongamento de vida, índice de reparabilidade têxtil e circuitos de retoma autorizados."],
  cirIndex: ["Textile repairability index", "Indice de Réparabilité Textile", "Textil-Reparierbarkeitsindex", "Indice di riparabilità tessile", "Índice de reparabilidad textil", "Textielrepareerbaarheidsindex", "Índice de reparabilidade têxtil"],
  cirIndexDesc: ["Reinforced bartacks, replaceable rib collar, single-material cotton thread.", "Points d'arrêt renforcés, col bord-côte remplaçable, fil coton monomatériau.", "Verstärkte Riegel, austauschbarer Rippkragen, Monomaterial-Baumwollgarn.", "Travette rinforzate, colletto a costine sostituibile, filo di cotone monomateriale.", "Presillas reforzadas, cuello de canalé sustituible, hilo de algodón monomaterial.", "Versterkte trenzen, vervangbare ribkraag, monomateriaal katoengaren.", "Remates reforçados, gola canelada substituível, linha de algodão monomaterial."],
  cirRecyclable: ["✓ 100% recyclable (single fibre)", "✓ Recyclable à 100% (Mono-Fibre)", "✓ Zu 100 % recycelbar (Monofaser)", "✓ Riciclabile al 100% (monofibra)", "✓ 100% reciclable (monofibra)", "✓ 100% recycleerbaar (monovezel)", "✓ 100% reciclável (monofibra)"],
  cirDisassembly: ["Disassembly and parts", "Démontabilité & Pièces", "Zerlegbarkeit und Teile", "Smontabilità e componenti", "Desmontabilidad y piezas", "Demonteerbaarheid en onderdelen", "Desmontabilidade e peças"],
  cirDisassemblyDesc: ["Standard detachable chain-stitch seams for simplified repair in an approved workshop.", "Coutures chaînette standard détachables pour réparation simplifiée en atelier agréé.", "Standardmäßige lösbare Kettenstichnähte für die vereinfachte Reparatur in einer zugelassenen Werkstatt.", "Cuciture a catenella standard staccabili per una riparazione semplificata in laboratorio autorizzato.", "Costuras de cadeneta estándar desmontables para una reparación simplificada en taller autorizado.", "Standaard losmaakbare kettingsteeknaden voor eenvoudige reparatie in een erkend atelier.", "Costuras de corrente padrão destacáveis para reparação simplificada em oficina autorizada."],
  cirBonus: ["Repair bonus (Refashion)", "Bonus Réparation (Refashion)", "Reparaturbonus (Refashion)", "Bonus riparazione (Refashion)", "Bono de reparación (Refashion)", "Reparatiebonus (Refashion)", "Bónus de reparação (Refashion)"],
  cirBonusAmount: ["Eligible for -€6 to -€15", "Éligible -6 € à -15 €", "Berechtigt für -6 € bis -15 €", "Idoneo da -6 € a -15 €", "Elegible de -6 € a -15 €", "In aanmerking voor -€6 tot -€15", "Elegível de -6 € a -15 €"],
  cirBonusDesc: ["Direct coverage at certified menders in the Refashion / AGEC network.", "Prise en charge directe chez les retoucheurs certifiés du réseau Refashion / AGEC.", "Direkte Kostenübernahme bei zertifizierten Änderungsschneidereien des Refashion-/AGEC-Netzes.", "Copertura diretta presso i sarti certificati della rete Refashion / AGEC.", "Cobertura directa en los talleres de arreglos certificados de la red Refashion / AGEC.", "Directe dekking bij gecertificeerde kledingherstellers in het Refashion-/AGEC-netwerk.", "Cobertura direta junto dos costureiros certificados da rede Refashion / AGEC."],
  cirEol: ["End of life and second life", "Fin de Vie & Seconde Vie", "Lebensende und zweites Leben", "Fine vita e seconda vita", "Fin de vida y segunda vida", "Einde levensduur en tweede leven", "Fim de vida e segunda vida"],
  cirSorting: ["Sorting and separate collection instructions", "Consignes de Tri & Collecte Sélective", "Hinweise zur Mülltrennung und getrennten Sammlung", "Istruzioni di smistamento e raccolta differenziata", "Instrucciones de clasificación y recogida selectiva", "Sorteer- en gescheiden-inzamelinstructies", "Instruções de triagem e recolha seletiva"],
  cirSortingDesc: ["Do not discard with household waste. Drop this T-shirt at one of the 46,000 Refashion collection points, or return it to a partner store for reuse or closed-loop mechanical shredding.", "Ne pas jeter avec les ordures ménagères. Déposez ce t-shirt dans l'un des 46 000 points d'apport volontaire (PAV) Refashion ou rapportez-le en boutique partenaire pour réemploi ou effilochage mécanique boucle-fermée.", "Nicht im Hausmüll entsorgen. Geben Sie dieses T-Shirt an einer der 46.000 Refashion-Sammelstellen ab oder bringen Sie es zur Wiederverwendung oder zum mechanischen Reißen im geschlossenen Kreislauf in ein Partnergeschäft.", "Non gettare nei rifiuti domestici. Deposita questa t-shirt in uno dei 46.000 punti di raccolta Refashion o riportala in un negozio partner per il riuso o lo sfilacciamento meccanico a circuito chiuso.", "No tirar con la basura doméstica. Deposite esta camiseta en uno de los 46.000 puntos de recogida Refashion o devuélvala a una tienda asociada para su reutilización o deshilachado mecánico en circuito cerrado.", "Niet bij het huisvuil weggooien. Lever dit T-shirt in bij een van de 46.000 Refashion-inzamelpunten of breng het terug naar een partnerwinkel voor hergebruik of mechanisch vervezelen in een gesloten kringloop.", "Não deitar no lixo doméstico. Deposite esta t-shirt num dos 46 000 pontos de recolha Refashion ou devolva-a numa loja parceira para reutilização ou desfibragem mecânica em circuito fechado."],
  gs1Title: ["GS1 Digital Link resolution and QR code", "Résolution GS1 Digital Link & QR Code", "GS1-Digital-Link-Auflösung und QR-Code", "Risoluzione GS1 Digital Link e QR code", "Resolución GS1 Digital Link y código QR", "GS1 Digital Link-resolutie en QR-code", "Resolução GS1 Digital Link e código QR"],
  gs1Desc: ["ISO/IEC 15459 standardised URI architecture linking the physical QR code sewn into the label to the secured digital passport.", "Architecture d'URI normalisée ISO/IEC 15459 reliant le QR code physique cousu sur l'étiquette au passeport numérique sécurisé.", "Nach ISO/IEC 15459 standardisierte URI-Architektur, die den im Etikett eingenähten physischen QR-Code mit dem gesicherten Digitalpass verbindet.", "Architettura URI normalizzata ISO/IEC 15459 che collega il QR code fisico cucito sull'etichetta al passaporto digitale protetto.", "Arquitectura de URI normalizada ISO/IEC 15459 que vincula el código QR físico cosido en la etiqueta con el pasaporte digital seguro.", "Volgens ISO/IEC 15459 genormaliseerde URI-architectuur die de fysieke QR-code in het label verbindt met het beveiligde digitale paspoort.", "Arquitetura de URI normalizada ISO/IEC 15459 que liga o código QR físico cosido na etiqueta ao passaporte digital seguro."],
  gs1Gtin: ["Global identifier of the textile style.", "Identifiant mondial du style textile.", "Globale Kennung des Textilmodells.", "Identificativo globale dello stile tessile.", "Identificador mundial del estilo textil.", "Wereldwijde identificatie van het textielmodel.", "Identificador mundial do modelo têxtil."],
  gs1Serial: ["Serial number (AI 21)", "Numéro de Série (AI 21)", "Seriennummer (AI 21)", "Numero di serie (AI 21)", "Número de serie (AI 21)", "Serienummer (AI 21)", "Número de série (AI 21)"],
  gs1SerialDesc: ["Granularity down to the making-up batch.", "Granularité au lot de confection.", "Granularität bis zur Konfektionscharge.", "Granularità fino al lotto di confezione.", "Granularidad hasta el lote de confección.", "Granulariteit tot de confectiebatch.", "Granularidade até ao lote de confeção."],
  sigSealed: ["Sealed by the immutable TRACEFAB registry", "Scellé par le registre immuable TRACEFAB", "Vom unveränderlichen TRACEFAB-Register versiegelt", "Sigillato dal registro immutabile TRACEFAB", "Sellado por el registro inmutable TRACEFAB", "Verzegeld door het onveranderlijke TRACEFAB-register", "Selado pelo registo imutável TRACEFAB"],
  sigTimestamp: ["Timestamping and cryptographic proof on Neon PostgreSQL", "Horodatage et preuve cryptographique Neon PostgreSQL", "Zeitstempel und kryptografischer Nachweis auf Neon PostgreSQL", "Marcatura temporale e prova crittografica su Neon PostgreSQL", "Sellado de tiempo y prueba criptográfica en Neon PostgreSQL", "Tijdstempel en cryptografisch bewijs op Neon PostgreSQL", "Carimbo temporal e prova criptográfica em Neon PostgreSQL"],
  sigViewSource: ["View ESPR source code", "Voir code source ESPR", "ESPR-Quellcode ansehen", "Visualizza il codice sorgente ESPR", "Ver el código fuente ESPR", "ESPR-broncode bekijken", "Ver o código-fonte ESPR"],
  ftCompliant: ["Digital passport aligned with the European Union Ecodesign Regulation (ESPR).", "Passeport Numérique aligné sur le Règlement Éco-conception de l'Union Européenne (ESPR).", "Digitaler Pass im Einklang mit der Ökodesign-Verordnung der Europäischen Union (ESPR).", "Passaporto digitale allineato al regolamento Ecodesign dell'Unione europea (ESPR).", "Pasaporte digital alineado con el Reglamento de Ecodiseño de la Unión Europea (ESPR).", "Digitaal paspoort afgestemd op de Ecodesignverordening van de Europese Unie (ESPR).", "Passaporte digital alinhado com o Regulamento de Conceção Ecológica da União Europeia (ESPR)."],
  ftPoweredBy: ["Powered by", "Propulsé par", "Betrieben von", "Realizzato con", "Desarrollado con", "Mogelijk gemaakt door", "Desenvolvido por"],
  ftReadiness: ["This passport follows the ESPR / CIRPASS data model. It is a readiness indicator, not a regulatory certification.", "Le format de ce passeport suit le modèle de données ESPR / CIRPASS. Il s'agit d'un indicateur de préparation, et non d'une certification réglementaire.", "Dieser Pass folgt dem ESPR-/CIRPASS-Datenmodell. Er ist ein Bereitschaftsindikator, keine regulatorische Zertifizierung.", "Questo passaporto segue il modello di dati ESPR / CIRPASS. È un indicatore di preparazione, non una certificazione normativa.", "Este pasaporte sigue el modelo de datos ESPR / CIRPASS. Es un indicador de preparación, no una certificación reglamentaria.", "Dit paspoort volgt het ESPR-/CIRPASS-datamodel. Het is een gereedheidsindicator, geen regelgevende certificering.", "Este passaporte segue o modelo de dados ESPR / CIRPASS. É um indicador de preparação, não uma certificação regulamentar."],
  jsonTitle: ["CIRPASS JSON-LD specification", "Spécification CIRPASS JSON-LD", "CIRPASS-JSON-LD-Spezifikation", "Specifica CIRPASS JSON-LD", "Especificación CIRPASS JSON-LD", "CIRPASS JSON-LD-specificatie", "Especificação CIRPASS JSON-LD"],
  jsonDesc: ["This standardised payload can be queried directly by European customs, CSRD auditors or textile sorting applications.", "Ce payload normalisé peut être interrogé directement par les douanes européennes, les auditeurs CSRD ou les applications de tri textile.", "Diese standardisierte Payload kann direkt vom europäischen Zoll, von CSRD-Prüfern oder von Textilsortieranwendungen abgefragt werden.", "Questo payload normalizzato può essere interrogato direttamente dalle dogane europee, dai revisori CSRD o dalle applicazioni di smistamento tessile.", "Esta carga útil normalizada puede ser consultada directamente por las aduanas europeas, los auditores CSRD o las aplicaciones de clasificación textil.", "Deze genormaliseerde payload kan rechtstreeks worden opgevraagd door de Europese douane, CSRD-auditors of textielsorteertoepassingen.", "Este payload normalizado pode ser consultado diretamente pelas alfândegas europeias, pelos auditores CSRD ou pelas aplicações de triagem têxtil."],
  metaTitle: ["Digital Product Passport — Organic Cotton Essential | TRACEFAB", "Passeport Numérique de Produit — Organic Cotton Essential | TRACEFAB", "Digitaler Produktpass — Organic Cotton Essential | TRACEFAB", "Passaporto digitale di prodotto — Organic Cotton Essential | TRACEFAB", "Pasaporte digital de producto — Organic Cotton Essential | TRACEFAB", "Digitaal productpaspoort — Organic Cotton Essential | TRACEFAB", "Passaporte digital de produto — Organic Cotton Essential | TRACEFAB"],
  metaDesc: ["Digital Product Passport (DPP) in ESPR / CIRPASS format for the Organic Cotton Essential style by Atelier Demo. Traceability, composition and repairability data.", "Passeport Numérique de Produit (DPP) au format ESPR / CIRPASS pour le style Organic Cotton Essential par Atelier Demo. Données de traçabilité, composition et réparabilité.", "Digitaler Produktpass (DPP) im ESPR-/CIRPASS-Format für das Modell Organic Cotton Essential von Atelier Demo. Daten zu Rückverfolgbarkeit, Zusammensetzung und Reparierbarkeit.", "Passaporto digitale di prodotto (DPP) in formato ESPR / CIRPASS per lo stile Organic Cotton Essential di Atelier Demo. Dati di tracciabilità, composizione e riparabilità.", "Pasaporte digital de producto (DPP) en formato ESPR / CIRPASS para el estilo Organic Cotton Essential de Atelier Demo. Datos de trazabilidad, composición y reparabilidad.", "Digitaal productpaspoort (DPP) in ESPR-/CIRPASS-formaat voor het model Organic Cotton Essential van Atelier Demo. Gegevens over traceerbaarheid, samenstelling en repareerbaarheid.", "Passaporte digital de produto (DPP) em formato ESPR / CIRPASS para o modelo Organic Cotton Essential da Atelier Demo. Dados de rastreabilidade, composição e reparabilidade."],
  ogDesc: ["Documented traceability from fibre to finished garment, in the format of the European ESPR regulation. A readiness indicator, not a certification.", "Traçabilité documentée de la fibre au vêtement fini, au format du Règlement européen ESPR. Indicateur de préparation, pas une certification.", "Dokumentierte Rückverfolgbarkeit von der Faser bis zum fertigen Kleidungsstück, im Format der europäischen ESPR-Verordnung. Ein Bereitschaftsindikator, keine Zertifizierung.", "Tracciabilità documentata dalla fibra al capo finito, nel formato del regolamento europeo ESPR. Un indicatore di preparazione, non una certificazione.", "Trazabilidad documentada de la fibra a la prenda acabada, en el formato del Reglamento europeo ESPR. Un indicador de preparación, no una certificación.", "Gedocumenteerde traceerbaarheid van vezel tot afgewerkt kledingstuk, in het formaat van de Europese ESPR-verordening. Een gereedheidsindicator, geen certificering.", "Rastreabilidade documentada da fibra à peça acabada, no formato do Regulamento europeu ESPR. Um indicador de preparação, não uma certificação."],
  tabEvidence: ["Evidence and audit", "Preuves & Audit", "Nachweise und Audit", "Prove e audit", "Pruebas y auditoría", "Bewijs en audit", "Provas e auditoria"],
  matTotalComposition: ["Total composition", "Composition totale", "Gesamtzusammensetzung", "Composizione totale", "Composición total", "Totale samenstelling", "Composição total"],
  matOrigin: ["Origin: Portugal (São Martinho farm)", "Origine : Portugal (Ferme São Martinho)", "Herkunft: Portugal (Hof São Martinho)", "Origine: Portogallo (fattoria São Martinho)", "Origen: Portugal (finca São Martinho)", "Herkomst: Portugal (boerderij São Martinho)", "Origem: Portugal (quinta São Martinho)"],
  matChemicals: ["Chemical substances", "Substances Chimiques", "Chemische Substanzen", "Sostanze chimiche", "Sustancias químicas", "Chemische stoffen", "Substâncias químicas"],
  matNonToxic: ["0% toxic", "0% Toxiques", "0 % toxisch", "0% tossiche", "0% tóxicas", "0% toxisch", "0% tóxicas"],
  matReach: ["REACH / OEKO-TEX Standard 100 — conformity shown only when documented.", "REACH & OEKO-TEX Standard 100 — conformité indiquée uniquement lorsqu'elle est documentée.", "REACH / OEKO-TEX Standard 100 — Konformität nur bei dokumentiertem Nachweis.", "REACH / OEKO-TEX Standard 100 — conformità indicata solo se documentata.", "REACH / OEKO-TEX Standard 100 — conformidad solo indicada cuando está documentada.", "REACH / OEKO-TEX Standard 100 — conformiteit alleen getoond wanneer gedocumenteerd.", "REACH / OEKO-TEX Standard 100 — conformidade apenas indicada quando documentada."],
  matMicrofibres: ["Plastic microfibres", "Microfibres Plastiques", "Plastik-Mikrofasern", "Microfibre plastiche", "Microfibras plásticas", "Plastic microvezels", "Microfibras plásticas"],
  matMicrofibresValue: ["0 g per wash", "0 g / lavage", "0 g pro Waschgang", "0 g per lavaggio", "0 g por lavado", "0 g per wasbeurt", "0 g por lavagem"],
  chainGotsCert: ["✓ GOTS certificate #CU-881294", "✓ Certificat GOTS #CU-881294", "✓ GOTS-Zertifikat #CU-881294", "✓ Certificato GOTS #CU-881294", "✓ Certificado GOTS #CU-881294", "✓ GOTS-certificaat #CU-881294", "✓ Certificado GOTS #CU-881294"],
  chainSpinning: ["Spinning and combing", "Filature & Peignage", "Spinnerei und Kämmerei", "Filatura e pettinatura", "Hilatura y peinado", "Spinnerij en kammen", "Fiação e penteação"],
  chainKnitting: ["Jersey knitting", "Tricotage Jersey", "Jersey-Strickerei", "Maglieria jersey", "Tejido de punto jersey", "Jersey breien", "Tricotagem jersey"],
  chainGauge: ["✓ Circular knit, 28 gauge", "✓ Maille circulaire jauge 28", "✓ Rundstrick, Feinheit 28", "✓ Maglia circolare, finezza 28", "✓ Punto circular, galga 28", "✓ Rondbreisel, naaldfijnheid 28", "✓ Malha circular, finura 28"],
  chainDyeing: ["Finishing and dyeing", "Ennoblissement & Teinture", "Veredelung und Färberei", "Nobilitazione e tintura", "Ennoblecimiento y tintura", "Veredeling en verven", "Acabamento e tingimento"],
  chainAssembly: ["Cutting, making-up and finishing", "Coupe, Confection & Finitions", "Zuschnitt, Konfektion und Finish", "Taglio, confezione e finissaggio", "Corte, confección y acabados", "Snijden, confectie en afwerking", "Corte, confeção e acabamentos"],
  chainSmeta: ["✓ SMETA 4-Pillar social audit (score A)", "✓ Audit social SMETA 4-Pillar (Score A)", "✓ SMETA-4-Säulen-Sozialaudit (Score A)", "✓ Audit sociale SMETA 4-Pillar (punteggio A)", "✓ Auditoría social SMETA 4-Pillar (puntuación A)", "✓ SMETA 4-Pillar sociale audit (score A)", "✓ Auditoria social SMETA 4-Pillar (pontuação A)"],
  impWater: ["Water consumption", "Consommation Hydrique", "Wasserverbrauch", "Consumo idrico", "Consumo de agua", "Waterverbruik", "Consumo de água"],
  impWaterValue: ["1,480 litres", "1,480 Litres", "1.480 Liter", "1.480 litri", "1.480 litros", "1.480 liter", "1.480 litros"],
  impMicroplastics: ["Microplastic release", "Relargage Microplastiques", "Mikroplastik-Freisetzung", "Rilascio di microplastiche", "Liberación de microplásticos", "Afgifte van microplastics", "Libertação de microplásticos"],
  impMicroValue: ["Grade A (none)", "Grade A (Nul)", "Stufe A (keine)", "Grado A (nullo)", "Grado A (nulo)", "Graad A (geen)", "Grau A (nulo)"],
  cirIndexValue: ["Index: 9.2/10", "Indice: 9.2/10", "Index: 9,2/10", "Indice: 9,2/10", "Índice: 9,2/10", "Index: 9,2/10", "Índice: 9,2/10"],
  cirEsprFormat: ["ESPR 2026 data model", "Modèle de données ESPR 2026", "ESPR-2026-Datenmodell", "Modello di dati ESPR 2026", "Modelo de datos ESPR 2026", "ESPR 2026-datamodel", "Modelo de dados ESPR 2026"],
  cirCollarHem: ["Collar and hem", "Col & Ourlet", "Kragen und Saum", "Colletto e orlo", "Cuello y dobladillo", "Kraag en zoom", "Gola e bainha"],
  evGotsRef: ["Certificate: CU-881294-GOTS-2026", "Certificat : CU-881294-GOTS-2026", "Zertifikat: CU-881294-GOTS-2026", "Certificato: CU-881294-GOTS-2026", "Certificado: CU-881294-GOTS-2026", "Certificaat: CU-881294-GOTS-2026", "Certificado: CU-881294-GOTS-2026"],
  evValid2027: ["Valid 2027", "Valide 2027", "Gültig 2027", "Valido 2027", "Válido 2027", "Geldig 2027", "Válido 2027"],
  evOekotex: ["OEKO-TEX Standard 100 — Class 1", "OEKO-TEX Standard 100 — Classe 1", "OEKO-TEX Standard 100 — Klasse 1", "OEKO-TEX Standard 100 — Classe 1", "OEKO-TEX Standard 100 — Clase 1", "OEKO-TEX Standard 100 — Klasse 1", "OEKO-TEX Standard 100 — Classe 1"],
  evOekotexRef: ["Report: 21.HPT.94112", "Rapport : 21.HPT.94112", "Bericht: 21.HPT.94112", "Rapporto: 21.HPT.94112", "Informe: 21.HPT.94112", "Rapport: 21.HPT.94112", "Relatório: 21.HPT.94112"],
  evValid2026: ["Valid 2026", "Valide 2026", "Gültig 2026", "Valido 2026", "Válido 2026", "Geldig 2026", "Válido 2026"],
  evCompliant: ["Compliant", "Conforme", "Konform", "Conforme", "Conforme", "Conform", "Conforme"],
  gs1Standard: ["GS1 standard 2026", "Standard GS1 2026", "GS1-Standard 2026", "Standard GS1 2026", "Estándar GS1 2026", "GS1-standaard 2026", "Norma GS1 2026"],
  gs1Uri: ["Official GS1 Digital Link URI:", "URI GS1 Digital Link Officielle :", "Offizielle GS1-Digital-Link-URI:", "URI GS1 Digital Link ufficiale:", "URI oficial GS1 Digital Link:", "Officiële GS1 Digital Link-URI:", "URI oficial GS1 Digital Link:"],
  gs1Ai01: ["Application identifier (AI 01)", "Code Application (AI 01)", "Anwendungskennzeichen (AI 01)", "Identificativo applicativo (AI 01)", "Identificador de aplicación (AI 01)", "Toepassingsidentificatie (AI 01)", "Identificador de aplicação (AI 01)"],
  jsonExport: ["Export CIRPASS JSON-LD", "Exporter JSON-LD CIRPASS", "CIRPASS JSON-LD exportieren", "Esporta CIRPASS JSON-LD", "Exportar CIRPASS JSON-LD", "CIRPASS JSON-LD exporteren", "Exportar CIRPASS JSON-LD"],
  // Etats explicites affiches par assets/js/dpp.2.js quand une donnee est
  // absente ou non verifiee : jamais une valeur de substitution.
  demoBanner: ["Demonstration passport — sample data, not a real product.", "Passeport de démonstration — données d'exemple, produit fictif.", "Demonstrationspass — Beispieldaten, kein echtes Produkt.", "Passaporto dimostrativo — dati di esempio, prodotto non reale.", "Pasaporte de demostración — datos de ejemplo, producto ficticio.", "Demonstratiepaspoort — voorbeelddata, geen echt product.", "Passaporte de demonstração — dados de exemplo, produto fictício."],
  statusUnverified: ["Not verified", "Non vérifié", "Nicht verifiziert", "Non verificato", "No verificado", "Niet geverifieerd", "Não verificado"],
  statusNotFilled: ["Not filled in", "Non renseigné", "Nicht ausgefüllt", "Non compilato", "No rellenado", "Niet ingevuld", "Não preenchido"],
  statusUnavailable: ["Unavailable", "Indisponible", "Nicht verfügbar", "Non disponibile", "No disponible", "Niet beschikbaar", "Indisponível"],
};

const keys = Object.keys(T);
const gaps = [];
for (const k of keys) {
  if (T[k].length !== LANGS.length) gaps.push(`${k}: ${T[k].length}/${LANGS.length}`);
  T[k].forEach((v, i) => { if (!v || !String(v).trim()) gaps.push(`${k}.${LANGS[i]} vide`); });
}
console.log(`  portee 'dpp' : ${keys.length} cles x ${LANGS.length} langues`);
if (gaps.length) { gaps.forEach((g) => console.log(`      ${g}`)); process.exit(1); }
console.log('  table complete, aucun trou.');

if (CHECK) { console.log('\n  --check : aucun fichier ecrit.'); process.exit(0); }

const scopeFor = (i) => Object.fromEntries(keys.map((k) => [k, T[k][i]]));

const enPath = join(I18N, 'en.js');
let enSrc = readFileSync(enPath, 'utf8');
// Le lookahead (?=\n\};) bornait la suppression a la fin de TOUT l'objet :
// le [\s\S]*? paresseux avalait donc chaque racine situee apres celle-ci.
// Tant que cette portee etait la derniere du catalogue, le resultat etait
// juste par accident. On borne desormais sur la fermeture de la portee
// elle-meme (accolade a 2 espaces), ce qui est independant de sa position.
enSrc = enSrc.replace(/,?\n\n  \/\/ --- DPP public[\s\S]*?\n  \}/, '');
const body = Object.entries(scopeFor(0)).map(([k, v]) => `    ${k}: ${JSON.stringify(v)}`).join(',\n');
enSrc = enSrc.replace(/\n\};\s*$/, `,\n\n  // --- DPP public --------------------------------------------------------\n  dpp: {\n${body}\n  }\n};\n`);
writeFileSync(enPath, enSrc);
console.log('\n  ecrit  assets/i18n/en.js');

LANGS.forEach((lang, i) => {
  if (lang === 'en') return;
  const p = join(I18N, `${lang}.json`);
  const d = JSON.parse(readFileSync(p, 'utf8'));
  d.dpp = scopeFor(i);
  writeFileSync(p, JSON.stringify(d, null, 2) + '\n');
  console.log(`  ecrit  assets/i18n/${lang}.json`);
});
